<?php
/**
 * Created by PhpStorm.
 * User: zhaoye
 * Date: 16/7/15
 * Time: 下午3:58
 */

namespace controller\Home;

use service\TestService;
use ZPHP\Cache\Factory;
use ZPHP\Cache\ICache;
use ZPHP\Client\SwoolePid;
use ZPHP\Controller\ApiController;
use ZPHP\Controller\Controller;
use ZPHP\Controller\WSController;
use ZPHP\Core\App;
use ZPHP\Core\Config;
use ZPHP\Core\Log;
use ZPHP\Core\Db;
use ZPHP\Coroutine\Base\TaskDistribute;
use ZPHP\Coroutine\Http\HttpClientCoroutine;
use ZPHP\Db\Mongo;
use ZPHP\Manager\Redis;
use ZPHP\Model\Model;

class Index extends Controller{
    protected function init()
    {
        $this->setApi();
        return parent::init(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $this->strReturn('Hello Zhttp!');
    }



    public function session(){
        //return $db;
//        $data = yield Db::table($db.'#')->query('SELECT * FROM `shechem_wx_wxuser` where openid=\'om0Kyvy_6C4s6ps_29ATAJK9cfkY\' limit 50');//->limit(10);
        //Log::write('12312312312');
        //return 'OK';
//        $data = $data['result'];
        //return debug_backtrace();
//        return $data;
        //单线程控制
            //向task 进程投递任务
        Log::write('session:'.json_encode($this->session));
        if(empty($this->session['vo'])) {
            $vo = yield table('users')->where('phone=14400001001')->find();
            $this->session['vo'] = $vo;
            $this->session['name'] = $vo['phone'];
        }
        $this->assign('vo', $this->session['vo']);


        $this->display();
//        $httpClient = new HttpClientCoroutine();
//        $data = $httpClient->request('http://wx.royldesign.cn/api/votes');
//        $default = yield Db::table('shechem_wx_wxuser')
//            ->where(['openid'=>'om0Kyv7zD6pzDaSQixDOZcs1VehE'])->find();
//        $read = yield Db::table('shechem_wx_wxuser', 'read')->where(['openid'=>'om0Kyv7zD6pzDaSQixDOZcs1VehE'])
//            ->find();
//        $default = [];
//        $read = [];
//        $this->jsonReturn(['d'=>$default, 'r'=>null]);
//        $data = yield Db::task()->callCoroutine(
//                array('class'=>'service\\InputMember',
//                    'method'=>'index',
//                    'param'=>[]
//                ));
//        $this->strReturn($data);
//        $res = yield Db::redis()->hmget('myhash', ['field1', 'field2']);
//        $res = yield Db::table('shechem_wx_wxuser')->where(['wxuserid'=>1])
//            ->find();
//        $res = 1;
//        $res = yield Db::redis()->set('account:wap:wxlogin:%s:%s', 'hello world!!!');
//        $this->jsonReturn($res);
//        $data = [
//          'class' => 'service/Test',
//            'method' => 'task',
//            'param' => ['helloworld!'],
//        ];
//        $taskResult = yield Db::task()->callCoroutine($data);//需要获取任务的结果
//        parse_str('', $content);
//        Db::task()->call($data);//只是发送任务，不需要获取任务的结果
//        return ['data'=>$taskResult,
//            'post'=>$this->request->post,'content'=>$content];
    }
    public function test(){
        $param = [
          'user_id' => intval($this->request->get['user_id']),
            'debug' => true,
        ];
        $info = yield table('users')->where('phone=14400001001')->find();
//        $info = yield App::model('Users')->getUserInfoByPhone(14400001001);
//        $param = 'user_id=5180125&debug=json';
//        Log::write('param:'.json_encode($param));
        $this->jsonReturn($info);
        //        $data = yield table('admin_user')->where(['id'=>1])->field('`id`,nickname')->find();
//
//        $this->jsonReturn(['data'=>$data,'sql'=> DB::getLastSql()]);
//        $this->assign('session', ['user'=>$data]);
//        $this->display();
    }


    public function getTest(){
        $data = yield App::service('test')->fuck();
        $this->assign('data', $data);
        $this->setTemplate('home');
        $this->display('index');
    }
    public function redis(){
        $data = yield Db::redis()->cache('abcd1');
        $this->strReturn($data);
//        $data = json_decode($data, true);
//        $this->assign('data', $data);
//        $this->display('index/index');
    }
    public function myempty(){
        $data = [['nickname'=>'Sven!']];
        $this->assign('data', $data);
        $this->setTemplate('home');
        $this->display('index');
    }
    public function mysql(){
        $data = yield Db::table('admin_user')->where(['id'=>1])->get();
        $this->assign('data', $data);
        $this->setTemplate('home');
        $this->display('index');
    }
    public function mongo(){
        $key = ['num'=>1];
        $initial = ['all'=>0,'no'=>0,'finish'=>0];
        $reduce = "function(obj, prev){prev.all=prev.all+obj.num}";
//         $group = yield Db::collection('hello')->where(['like'=>['lte',5]])->group($key, $initial, $reduce);
        // $aggregate = yield Db::collection('hello')->where(['])->setInc('num');
//        $finddata = yield Db::collection('test')->where(['likes'=>100])->find();
//        $getdata = yield Db::collection('test')->where(['likes'=>100])->get();
//        $count = yield Db::collection('hello')->where(['like'=>['elt',5]])->count();
        $data = yield Db::collection('hello')->where(['title'=>'MongoDB0'])->get();
        $this->assign('data', $data);
        $this->setTemplate('home');
        $this->display('index');
    }
}